version: 0.2
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUM_USER} --password-stdin
  build:
    commands:
      - echo "running mvn install"
      - mvn clean install
      - docker build -t aws-code-pipeline:$CODEBUILD_BUILD_NUMBER .
  post_build:
    commands:
      - docker tag aws-code-pipeline:$CODEBUILD_BUILD_NUMBER ${DOCKERHUM_USER}/aws-code-pipeline:$CODEBUILD_BUILD_NUMBER
      - docker push ${DOCKERHUM_USER}/aws-code-pipeline:$CODEBUILD_BUILD_NUMBER